-- ===========================================================================
-- MIGRATION B (S9) — drop the per-module sale tables.
--
-- 🔴 THE POINT OF NO RETURN. There is no undo; a restore from a dump is the
-- only way back. Run it ONLY against a database whose backup you have opened
-- and verified by contents (a known row is in it, it ends with
-- "PostgreSQL database dump complete", and it contains COPY data blocks).
--
-- WHY THIS DESTROYS NOTHING
-- -------------------------
-- Every bill these tables held was copied into "Sale"/"SaleItem" by Migration A
-- and S5, KEEPING THE SAME id. That is why the app carried a de-duplication
-- filter for as long as both existed, and why it could be deleted the moment
-- these tables did. Checked immediately before this file was written:
--
--   BeverageSale        0 rows
--   BeverageSaleItem    0 rows
--   BakerySale          1 row   -- Rs. 5,000, already in "Sale" with the same id
--   BakerySaleItem      1 row
--   MilkSale            1 row   -- Rs. 6,000, already in "Sale" with the same id
--   Sale / SaleItem     2 / 2
--
-- RE-CHECK THOSE COUNTS BEFORE RUNNING. If a row exists here that is NOT in
-- "Sale", stop: it has not been migrated and this would delete it.
--
-- MilkSale is included with the owner's explicit approval (2026-08-18). It was
-- outside Migration B's original scope, which predated the milk cutover.
--
-- NOTHING READS THESE TABLES. Verified by grep across app/, lib/ and
-- components/ before this was generated; the last reader was the dedupe filter,
-- which this change removes.
--
-- Generated by `prisma migrate diff --from-schema-datasource … --script`, the
-- READ-ONLY form. It introspects and writes nothing. NEVER generate a migration
-- with --shadow-database-url pointed at a real database: that flag DROPS EVERY
-- OBJECT in whatever you give it, and it is what destroyed this project's
-- production database on 2026-08-12.
--
-- No CASCADE anywhere below, deliberately: the foreign keys are dropped one by
-- one first, so if some object we do not know about still depends on these
-- tables, this fails loudly instead of quietly taking that object with it.
-- ===========================================================================

-- DropForeignKey
ALTER TABLE "BakerySale" DROP CONSTRAINT "BakerySale_customerId_fkey";

-- DropForeignKey
ALTER TABLE "BakerySaleItem" DROP CONSTRAINT "BakerySaleItem_productId_fkey";

-- DropForeignKey
ALTER TABLE "BakerySaleItem" DROP CONSTRAINT "BakerySaleItem_saleId_fkey";

-- DropForeignKey
ALTER TABLE "BeverageSale" DROP CONSTRAINT "BeverageSale_customerId_fkey";

-- DropForeignKey
ALTER TABLE "BeverageSaleItem" DROP CONSTRAINT "BeverageSaleItem_productId_fkey";

-- DropForeignKey
ALTER TABLE "BeverageSaleItem" DROP CONSTRAINT "BeverageSaleItem_saleId_fkey";

-- DropForeignKey
ALTER TABLE "MilkSale" DROP CONSTRAINT "MilkSale_customerId_fkey";

-- DropTable
DROP TABLE "BakerySale";

-- DropTable
DROP TABLE "BakerySaleItem";

-- DropTable
DROP TABLE "BeverageSale";

-- DropTable
DROP TABLE "BeverageSaleItem";

-- DropTable
DROP TABLE "MilkSale";

